/* Scene 8 + footer audit sweep (Phase 4 · Step 8). Run: NODE_PATH=./node_modules node audit/scene-return.cjs  (dev :3000, prod :3100). */
const puppeteer=require('puppeteer');const fs=require('fs');const U='http://localhost:3000';const P='http://localhost:3100';const sleep=ms=>new Promise(r=>setTimeout(r,ms));const OUT='/home/user/shots22';fs.mkdirSync(OUT,{recursive:true});
const R={};
(async()=>{const b=await puppeteer.launch({args:['--no-sandbox','--disable-setuid-sandbox']});
const newPage=async(o={})=>{const p=await b.newPage();await p.setViewport({width:o.w||1280,height:o.h||800});if(o.rm)await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);p._hyd=[];p.on('console',m=>{const t=m.text();if(/hydrat|did not match|Warning:|error/i.test(t))p._hyd.push(t.slice(0,160))});return p;};
const home=async(p,theme,base=U)=>{await p.goto(base+'/',{waitUntil:'networkidle0'});await p.evaluate(()=>document.documentElement.style.scrollBehavior='auto');if(theme)await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);};

/* 1. NO-JS — strings, links, structure */
{const p=await newPage();await p.setJavaScriptEnabled(false);await p.goto(P+'/',{waitUntil:'networkidle0'});
 R.nojs=await p.evaluate(()=>{const txt=n=>(n.textContent||'').replace(/\s+/g,' ').trim();const s=document.querySelector('[data-scene=return]');const f=document.querySelector('footer');return{
  sceneStrings:[...s.querySelectorAll('h2,p,a')].map(txt).filter(Boolean),footerStrings:[...f.querySelectorAll('p,a,nav')].map(e=>e.tagName==='NAV'?'nav['+e.getAttribute('aria-label')+']':txt(e)+(e.getAttribute('aria-label')?' [aria-label='+e.getAttribute('aria-label')+']':'')),
  links:[...document.querySelectorAll('[data-scene=return] a, footer a')].map(a=>({text:txt(a)||a.getAttribute('aria-label'),href:a.getAttribute('href')})),
  footerOutsideSpine:!document.querySelector('[data-spine] footer')&&!!document.querySelector('main + footer, main ~ footer'),footerCount:document.querySelectorAll('footer').length,
  footerParent:f.parentElement.tagName+'.'+f.parentElement.className.split(' ')[0],prevSibling:f.previousElementSibling.tagName+'#'+f.previousElementSibling.id,
  headings:[...document.querySelectorAll('h1,h2,h3')].slice(-3).map(h=>h.tagName+':'+txt(h).slice(0,40)),footerHeadings:f.querySelectorAll('h1,h2,h3,h4').length,
  focusablesInScene:s.querySelectorAll('a,button,input,[tabindex]').length,forms:document.querySelectorAll('footer form, footer input, [data-scene=return] form, [data-scene=return] input').length,imgs:s.querySelectorAll('img,canvas,video').length,footerSvg:f.querySelectorAll('svg').length,
  primariesVisible:null,
  pageWords:[...document.querySelectorAll('section[data-scene]')].map(x=>{x.querySelectorAll('[data-scene-meta],style').forEach(n=>n.remove());return [x.getAttribute('data-scene'),(x.textContent||'').trim().split(/\s+/).length]}).concat([['footer',txt(f).split(' ').length]])}});
 await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await sleep(200);await p.screenshot({path:`${OUT}/end-nojs.png`});await p.close();}

/* 2. DEAD-LINK sweep on prod */
{const p=await newPage();R.links=[];for(const l of R.nojs.links){const href=l.href;const url=href.startsWith('#')?P+'/'+href:href.startsWith('/')?P+href:href;const path=url.split('#')[0];const r=await p.goto(path,{waitUntil:'load'});let anchorOk=null;if(url.includes('#')){anchorOk=await p.evaluate(id=>!!document.getElementById(id),url.split('#')[1]);}R.links.push({text:l.text,href,status:r.status(),anchorResolves:anchorOk});}await p.close();}

/* 3. PAGE END + geometry + scroll budget + primaries + footer proportion + brand colour */
for(const theme of ['dark','light']){const p=await newPage();await home(p,theme,P);
 const g=await p.evaluate(()=>{const s=document.querySelector('[data-scene=return]');const f=document.querySelector('footer');const doc=document.documentElement;const r=s.getBoundingClientRect();const fr=f.getBoundingClientRect();
  const prim=[...document.querySelectorAll('a,button')].filter(e=>/primary/.test(e.className)||e.matches('[data-return-action]'));return{sceneVh:+(r.height/innerHeight).toFixed(2),contentVh:+(s.firstElementChild.getBoundingClientRect().height/innerHeight).toFixed(2),footerH:Math.round(fr.height),pageH:doc.scrollHeight,footerPct:+(fr.height/doc.scrollHeight*100).toFixed(2),
  footerBottomEqualsPageBottom:Math.abs(fr.bottom+scrollY-doc.scrollHeight)<2,trailingAfterFooter:doc.scrollHeight-Math.round(fr.bottom+scrollY),
  markFill:(()=>{const svg=f.querySelector('svg');const el=svg&&(svg.querySelector('[stroke]')||svg.querySelector('[fill]'));return el?(getComputedStyle(el).stroke!=='none'?getComputedStyle(el).stroke:getComputedStyle(el).fill):getComputedStyle(svg).color})(),
  footerSubjectAttr:!!f.closest('[data-subject]')||!!f.querySelector('[data-subject]'),
  primaryButtons:prim.map(e=>({text:e.textContent.trim(),top:Math.round(e.getBoundingClientRect().top+scrollY),scene:e.closest('section')?.getAttribute('data-scene')}))}});
 await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await sleep(300);
 const end=await p.evaluate(()=>{const s=document.querySelector('[data-scene=return]');const f=document.querySelector('footer');const prim=[...document.querySelectorAll('a,button')].filter(e=>/primary/.test(e.className)||e.matches('[data-return-action]')).filter(e=>{const r=e.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight});return{footerTopInViewport:Math.round(f.getBoundingClientRect().top),footerStartsMidViewport:f.getBoundingClientRect().top>innerHeight*0.5,sceneVisible:s.getBoundingClientRect().bottom>0,primariesVisibleAtEnd:prim.map(e=>e.textContent.trim()+'@'+e.closest('section')?.getAttribute('data-scene')),cta:(()=>{const a=document.querySelector('[data-return-action]');const r=a.getBoundingClientRect();return{w:Math.round(r.width),h:Math.round(r.height)}})(),footerLinks:[...document.querySelectorAll('footer a')].map(a=>{const r=a.getBoundingClientRect();return Math.round(r.width)+'x'+Math.round(r.height)})}});
 R['end_'+theme]={...g,...end,hydration:p._hyd};await p.screenshot({path:`${OUT}/end-${theme}-1280.png`});
 /* focus ring visible */
 await p.evaluate(()=>document.querySelector('[data-return-action]').focus());const ring=await p.evaluate(()=>{const a=document.querySelector('[data-return-action]');const cs=getComputedStyle(a);return{outline:cs.outlineStyle+' '+cs.outlineWidth+' '+cs.outlineColor,boxShadow:cs.boxShadow.slice(0,60)}});R['end_'+theme].focusRing=ring;if(theme==='dark')await p.screenshot({path:`${OUT}/cta-focus.png`,clip:{x:0,y:0,width:1280,height:800}});
 await p.close();}

/* 4. KEYBOARD — from Scene 8 to end */
{const p=await newPage();await home(p,'dark',P);await p.evaluate(()=>document.querySelector('[data-scene=promise] h2').scrollIntoView());const stops=[];for(let i=0;i<40;i++){await p.keyboard.press('Tab');const s=await p.evaluate(()=>{const a=document.activeElement;const sc=a.closest('section[data-scene]');const f=a.closest('footer');return (sc?sc.getAttribute('data-scene'):f?'footer':'chrome')+':'+a.tagName+':'+(a.getAttribute('aria-label')||a.textContent||'').trim().slice(0,22)});stops.push(s);if(stops.filter(x=>x==='chrome:BODY:').length>1)break;}
 /* also from the enter scene onwards */
 const idx=stops.findIndex(s=>s.startsWith('return'));R.keyboard={fromEnter:stops.slice(0,idx+8),returnAndFooter:stops.slice(idx,idx+6)};await p.close();}

/* 5. RM + widths + zoom + text spacing (dev frames) */
{const p=await newPage({rm:true});await home(p,'dark',P);await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await sleep(200);R.rm=await p.evaluate(()=>({motionClasses:document.querySelectorAll('[data-scene=return] .ta-reveal,[data-scene=return] .ta-stagger').length,visible:getComputedStyle(document.querySelector('[data-return]')).opacity}));await p.screenshot({path:`${OUT}/end-rm.png`});await p.close();
 R.widths=[];for(const t of ['dark','light'])for(const w of [320,390,768,1280,1920]){const q=await newPage({w,h:900});await q.goto(`${U}/dev/scene-return?frame=both&theme=${t}`,{waitUntil:'load'});await sleep(300);
  R.widths.push({t,w,...await q.evaluate(()=>{const f=document.querySelector('footer');const a=document.querySelector('[data-return-action]');const r=a.getBoundingClientRect();const links=[...f.querySelectorAll('a')].map(x=>x.getBoundingClientRect());const gaps=links.slice(1).map((r2,i)=>Math.round(Math.max(r2.left-links[i].right,r2.top-links[i].bottom)));return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,footerH:Math.round(f.getBoundingClientRect().height),footerRows:new Set([...f.querySelectorAll('a,p')].map(e=>Math.round(e.getBoundingClientRect().top))).size,cta:Math.round(r.width)+'x'+Math.round(r.height),ctaFullWidth:r.width>=document.documentElement.clientWidth-60,minLinkGap:Math.min(...gaps)}})});if(t==='dark'&&(w===320||w===1280||w===1920))await q.screenshot({path:`${OUT}/both-${w}.png`,fullPage:true});await q.close();}
 const z=await newPage({w:1280,h:800});await z.goto(P+'/',{waitUntil:'networkidle0'});R.zoom={};for(const f of [2,4]){await z.setViewport({width:1280/f,height:800/f});await sleep(300);await z.evaluate(()=>scrollTo(0,document.body.scrollHeight));await sleep(200);R.zoom['z'+f*100]=await z.evaluate(()=>{const doc=document.documentElement;const f=document.querySelector('footer');return{overflow:doc.scrollWidth>doc.clientWidth,footerBottomAtPageEnd:Math.abs(f.getBoundingClientRect().bottom+scrollY-doc.scrollHeight)<2,clipped:[...document.querySelectorAll('[data-scene=return] p,[data-scene=return] a,footer a,footer p')].some(e=>e.scrollWidth>e.clientWidth+1)}});if(f===4)await z.screenshot({path:`${OUT}/end-zoom400.png`});}
 await z.setViewport({width:1280,height:800});await z.evaluate(()=>{const s=document.createElement('style');s.textContent='*{line-height:1.5!important;letter-spacing:.12em!important;word-spacing:.16em!important}p{margin-bottom:2em!important}';document.head.appendChild(s)});await sleep(200);R.textSpacing=await z.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,clipped:[...document.querySelectorAll('[data-scene=return] *,footer *')].filter(e=>e.children.length===0).some(e=>e.scrollWidth>e.clientWidth+1)}));await z.close();
 const gq=await newPage();await gq.goto(`${U}/dev/scene-return?frame=both&gray=1`,{waitUntil:'load'});await sleep(300);await gq.screenshot({path:`${OUT}/both-gray.png`});await gq.close();
 const zr=await newPage();await zr.goto(`${U}/dev/scene-return?frame=scene&ready=0`,{waitUntil:'load'});R.zeroReady=await zr.evaluate(()=>({open:document.querySelector('[data-return-open]')?.textContent,action:document.querySelector('[data-return-action]')?.textContent,href:document.querySelector('[data-return-action]')?.getAttribute('href')}));await zr.screenshot({path:`${OUT}/zero-ready.png`});await zr.close();}

/* 6. Payload + WebGL + CLS full scroll + long tasks */
{const p=await newPage();const reqs=[];p.on('response',r=>reqs.push({u:r.url(),len:+(r.headers()['content-length']||0)}));await home(p,null,P);
 await p.evaluate(()=>{window.__cls=0;new PerformanceObserver(l=>{for(const e of l.getEntries())if(!e.hadRecentInput)window.__cls+=e.value}).observe({type:'layout-shift',buffered:true});window.__long=[];try{new PerformanceObserver(l=>{for(const e of l.getEntries())window.__long.push(Math.round(e.duration))}).observe({entryTypes:['longtask']})}catch{}});
 const H=await p.evaluate(()=>document.body.scrollHeight);for(let y=0;y<=H;y+=300){await p.evaluate(v=>scrollTo(0,v),y);await sleep(40);}await sleep(500);
 R.perf={requests:reqs.length,bytes:reqs.reduce((a,r)=>a+r.len,0),webgl:reqs.filter(r=>/three|webgl|ambient/i.test(r.u)).length,canvas:await p.evaluate(()=>document.querySelectorAll('canvas').length),clsFullScroll:await p.evaluate(()=>+window.__cls.toFixed(4)),long:await p.evaluate(()=>window.__long),pageH:H,scenes:await p.evaluate(()=>[...document.querySelectorAll('section[data-scene]')].map(s=>[s.getAttribute('data-scene'),+(s.getBoundingClientRect().height/innerHeight).toFixed(2)])),motifs:await p.evaluate(()=>({surfaces:document.querySelectorAll('[data-motif]').length,paths:[...document.querySelectorAll('[data-motif] path')].reduce((a,p)=>a+(p.getAttribute('d')||'').split(/[MLHVCSQTAZ]/i).length-1,0),dom:[...document.querySelectorAll('[data-motif]')].reduce((a,m)=>a+m.querySelectorAll('*').length,0)}))};
 R.prod404=(await p.goto(P+'/dev/scene-return',{waitUntil:'load'})).status();await p.close();}

await b.close();fs.writeFileSync('/tmp/s8.json',JSON.stringify(R,null,1));console.log(JSON.stringify(R,null,1));})();
