/* Scene 4 audit sweep (Phase 4 · Step 5). Run: NODE_PATH=./node_modules node audit/scene-enter.cjs  (dev server on :3000) */
const puppeteer=require('puppeteer');const fs=require('fs');const U='http://localhost:3000';const sleep=ms=>new Promise(r=>setTimeout(r,ms));const OUT='/home/user/shots19';fs.mkdirSync(OUT,{recursive:true});
const R={};
(async()=>{const b=await puppeteer.launch({args:['--no-sandbox','--disable-setuid-sandbox']});
const newPage=async(o={})=>{const p=await b.newPage();await p.setViewport({width:o.w||1280,height:o.h||800,deviceScaleFactor:o.dpr||1});if(o.cores)await p.evaluateOnNewDocument(c=>Object.defineProperty(navigator,'hardwareConcurrency',{get:()=>c}),o.cores);if(o.rm)await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);p._hyd=[];p.on('console',m=>{const t=m.text();if(/hydrat|did not match|Warning:/i.test(t))p._hyd.push(t.slice(0,160))});return p;};
const gotoScene=async(p,theme)=>{await p.goto(U+'/',{waitUntil:'networkidle0'});await p.evaluate(()=>document.documentElement.style.scrollBehavior='auto');if(theme)await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await p.evaluate(()=>document.querySelector('[data-scene=enter]').scrollIntoView({block:'start'}));await sleep(500);};

/* 1. WALK — tiers, announcements, focus, layers, CLS, frames, brand-frame invariance (both themes, 8 cores → desktop-class) */
for(const theme of ['dark','light']){const p=await newPage({cores:8});await gotoScene(p,theme);
 await p.evaluate(()=>{window.__cls=0;new PerformanceObserver(l=>{for(const e of l.getEntries())if(!e.hadRecentInput)window.__cls+=e.value}).observe({type:'layout-shift',buffered:true});window.__ann=[];const live=document.querySelector('[data-scene=enter] [data-switch-announce]');new MutationObserver(()=>window.__ann.push(live.textContent)).observe(live,{childList:true,subtree:true,characterData:true});window.__layersMax=1;window.__frames=[];let last=-1;const rec=()=>{const n=performance.now();if(last>=0)window.__frames.push(n-last);last=n;window.__layersMax=Math.max(window.__layersMax,document.querySelectorAll('[data-scene=enter] [data-switch-layer]').length);requestAnimationFrame(rec)};requestAnimationFrame(rec);window.__long=[];try{new PerformanceObserver(l=>{for(const e of l.getEntries())window.__long.push(Math.round(e.duration))}).observe({entryTypes:['longtask']})}catch{}});
 const headerBefore=await p.screenshot({clip:{x:0,y:0,width:1280,height:40},encoding:'base64'});
 await p.evaluate(()=>document.querySelector('[data-enter-next]').focus());
 const steps=[];const hdrDiffs=[];
 for(let i=0;i<6;i++){await p.keyboard.press('Enter');await sleep(150);const mid=await p.evaluate(()=>({layers:document.querySelectorAll('[data-scene=enter] [data-switch-layer]').length,opac:[...document.querySelectorAll('[data-scene=enter] [data-switch-layer]')].map(l=>l.getAttribute('data-switch-layer')+':'+(+getComputedStyle(l).opacity).toFixed(2))}));const hdrMid=await p.screenshot({clip:{x:0,y:0,width:1280,height:40},encoding:'base64'});hdrDiffs.push(hdrMid===headerBefore);if(i===1&&theme==='dark')await p.screenshot({path:`${OUT}/s4-mid-transition.png`});await sleep(1700);
  const s=await p.evaluate(()=>({focus:document.activeElement?.getAttribute('data-enter-next')!=null?'next-button':document.activeElement?.tagName,ann:window.__ann.slice(),layers:document.querySelectorAll('[data-scene=enter] [data-switch-layer]').length,cta:document.querySelector('[data-enter-cta]')?.getAttribute('href')||document.querySelector('[data-enter-status]')?.textContent,pos:document.querySelector('[data-enter-position]').textContent,name:document.querySelector('[data-enter-name]').textContent,tier:document.querySelector('[data-enter]').getAttribute('data-enter-tier')}));steps.push({...s,ann:s.ann[s.ann.length-1],annCount:s.ann.length,mid});
  if(theme==='dark')await p.screenshot({path:`${OUT}/s4-walk-${i+1}-${s.name}.png`});}
 const tail=await p.evaluate(()=>({cls:window.__cls,ann:window.__ann,layersMax:window.__layersMax,frames:{n:window.__frames.length,avg:+(window.__frames.reduce((a,b)=>a+b,0)/window.__frames.length).toFixed(1),worst:+Math.max(...window.__frames).toFixed(1),over50:window.__frames.filter(f=>f>50).length},long:window.__long}));
 R['walk_'+theme]={steps,...tail,headerIdenticalMidTransition:hdrDiffs,hydration:p._hyd};
 if(theme==='dark'){await p.screenshot({path:`${OUT}/s4-dark-1280.png`});}else await p.screenshot({path:`${OUT}/s4-light-1280.png`});
 await p.close();}

/* 1b. tier telemetry via dev page (engine's own readout) — deliberate walk then return step + rapid */
{const p=await newPage({cores:8});await p.goto(U+'/dev/scene-enter',{waitUntil:'networkidle0'});await sleep(800);
 await p.evaluate(()=>document.querySelector('[data-iso=enter]').scrollIntoView());
 const btn=await p.$('[data-iso=enter] [data-enter-next]');await btn.focus();
 for(let i=0;i<7;i++){await p.keyboard.press('Enter');await sleep(1900);}
 await p.keyboard.press('Enter');await sleep(80);await p.keyboard.press('Enter');await sleep(80);await p.keyboard.press('Enter');await sleep(1200);
 R.tierTable=await p.evaluate(()=>[...document.querySelectorAll('[data-tier-table] tbody tr')].map(tr=>[...tr.children].map(td=>td.textContent).join(' | ')));
 R.devHydration=p._hyd;await p.close();}

/* 2. INTERRUPTION — rapid, mid-transition retarget, navigate away mid-transition */
{const p=await newPage({cores:8});await gotoScene(p,'dark');
 const r=await p.evaluate(async()=>{const s=ms=>new Promise(r=>setTimeout(r,ms));const next=document.querySelector('[data-enter-next]');const prev=document.querySelector('[data-enter-prev]');const L=()=>document.querySelectorAll('[data-scene=enter] [data-switch-layer]').length;
  next.click();await s(120);prev.click();await s(120);next.click();await s(120);next.click();const midL=L();await s(1500);const afterL=L();const name=document.querySelector('[data-enter-name]').textContent;const pos=document.querySelector('[data-enter-position]').textContent;const op=[...document.querySelectorAll('[data-scene=enter] [data-switch-layer]')].map(l=>l.getAttribute('data-switch-layer')+':'+getComputedStyle(l).opacity);
  return {midLayers:midL,afterLayers:afterL,name,pos,op,converged:name===pos.split(' · ')[0]&&afterL===1}});
 R.interrupt=r;
 await p.evaluate(()=>document.querySelector('[data-enter-next]').click());await sleep(150);await p.goto(U+'/subjects/mathematics',{waitUntil:'networkidle0'});R.navigateAwayMidTransition={landed:p.url(),errors:p._hyd};await p.close();}

/* 3. NO-JS */
{const p=await newPage();await p.setJavaScriptEnabled(false);await p.goto(U+'/',{waitUntil:'networkidle0'});await p.evaluate(()=>document.querySelector('[data-scene=enter]').scrollIntoView({block:'start'}));await sleep(300);await p.screenshot({path:`${OUT}/s4-nojs.png`});
 R.nojs=await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');const st=s.firstElementChild;return {sectionH:Math.round(s.getBoundingClientRect().height),stickyPos:getComputedStyle(st).position,layers:s.querySelectorAll('[data-switch-layer]').length,paths:s.querySelectorAll('[data-switch-layer] path').length,name:s.querySelector('[data-enter-name]').textContent,env:s.querySelector('[data-enter-env]').textContent,tagline:s.querySelector('[data-enter-tagline]').textContent,cta:s.querySelector('[data-enter-cta]')?.getAttribute('href'),controlVisibility:getComputedStyle(s.querySelector('[data-enter-control]')).visibility,markColor:getComputedStyle(s.querySelector('[data-enter-mark]')).color,focusable:[...s.querySelectorAll('a,button')].filter(e=>e.offsetParent&&getComputedStyle(e).visibility!=='hidden').map(e=>e.textContent.trim())}});
 await p.close();}

/* 4. STICKY — hold + release, no scroll-jacking (wheel/keyboard/scrollbar-equivalent), 400% zoom proxy, short viewport, RM, widths */
{const p=await newPage({cores:8});await p.goto(U+'/',{waitUntil:'networkidle0'});await p.evaluate(()=>document.documentElement.style.scrollBehavior='auto');
 const top=await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');return scrollY+s.getBoundingClientRect().top});
 const probe=async(dy)=>{await p.evaluate(y=>scrollTo(0,y),top+dy);await sleep(120);return p.evaluate(()=>{const st=document.querySelector('[data-scene=enter]').firstElementChild;return {y:scrollY,stickyTop:Math.round(st.getBoundingClientRect().top),stageTop:Math.round(document.querySelector('[data-enter-stage]').getBoundingClientRect().top)}})};
 R.sticky={at0:await probe(0),at200:await probe(200),at400:await probe(400),at480:await probe(480),at700:await probe(700),at1200:await probe(1200)};
 // wheel: each wheel tick must move scrollY by the native amount (no interception)
 await p.evaluate(y=>scrollTo(0,y),top+100);await sleep(100);const y0=await p.evaluate(()=>scrollY);await p.mouse.move(640,400);await p.mouse.wheel({deltaY:300});await sleep(400);const y1=await p.evaluate(()=>scrollY);await p.keyboard.press('PageDown');await sleep(600);const y2=await p.evaluate(()=>scrollY);await p.keyboard.press('End');await sleep(800);const y3=await p.evaluate(()=>({y:scrollY,max:document.documentElement.scrollHeight-innerHeight}));
 R.noScrollJack={wheelDelta:y1-y0,pageDownDelta:y2-y1,endReachesBottom:y3.y>=y3.max-2,listeners:await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');return {sectionOnWheel:!!s.onwheel,bodyOverflow:getComputedStyle(document.body).overflow,htmlScrollBehavior:getComputedStyle(document.documentElement).scrollBehavior,overscroll:getComputedStyle(document.documentElement).overscrollBehavior}})};
 await p.close();}
for(const [label,w,h,rm] of [['zoom400',320,200,false],['short',900,400,false],['rm',1280,800,true]]){const p=await newPage({w,h,rm});await gotoScene(p,'dark');R['sticky_'+label]=await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');return {sectionH:Math.round(s.getBoundingClientRect().height),innerH:innerHeight,stickyPos:getComputedStyle(s.firstElementChild).position,scrollW:document.documentElement.scrollWidth,vw:innerWidth}});await p.screenshot({path:`${OUT}/s4-sticky-${label}.png`});
 if(rm){await p.evaluate(()=>document.querySelector('[data-enter-next]').click());await sleep(60);R.rmStep=await p.evaluate(()=>({layersRightAfter:document.querySelectorAll('[data-scene=enter] [data-switch-layer]').length,name:document.querySelector('[data-enter-name]').textContent,ann:document.querySelector('[data-scene=enter] [data-switch-announce]').textContent}));await sleep(300);await p.screenshot({path:`${OUT}/s4-reduced.png`});}
 await p.close();}
for(const w of [320,390,768,1280,1920]){const p=await newPage({w,h:w<=390?844:w===768?1024:w===1920?1080:800});for(const theme of ['dark','light']){await gotoScene(p,theme);const m=await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');const st=s.firstElementChild;const stage=document.querySelector('[data-enter-stage]').getBoundingClientRect();const btns=[...document.querySelectorAll('[data-enter-control] button, [data-enter-cta]')].map(b=>{const r=b.getBoundingClientRect();return Math.round(r.width)+'x'+Math.round(r.height)});return {sticky:getComputedStyle(st).position,sectionH:Math.round(s.getBoundingClientRect().height),vh:+(s.getBoundingClientRect().height/innerHeight).toFixed(2),stage:Math.round(stage.width)+'x'+Math.round(stage.height),scrollW:document.documentElement.scrollWidth,targets:btns,contentFits:document.querySelector('[data-enter]').getBoundingClientRect().height<=innerHeight}});R[`width_${w}_${theme}`]=m;if(theme==='dark'){await p.evaluate(()=>document.querySelector('[data-enter-stage]').scrollIntoView({block:'center'}));await sleep(200);await p.screenshot({path:`${OUT}/s4-${w}.png`});}}await p.close();}

/* 5. GRAYSCALE + text spacing + zoom200 proxy + focus rings + primary count */
{const p=await newPage();await gotoScene(p,'dark');await p.evaluate(()=>document.querySelector('[data-enter-stage]').style.filter='grayscale(1)');await sleep(200);await p.screenshot({path:`${OUT}/s4-grayscale.png`});
 await p.addStyleTag({content:'*{line-height:1.5 !important;letter-spacing:.12em !important;word-spacing:.16em !important} p{margin-bottom:2em !important}'});await sleep(200);R.textSpacing=await p.evaluate(()=>({scrollW:document.documentElement.scrollWidth,clipped:[...document.querySelectorAll('[data-scene=enter] *')].filter(e=>e.scrollWidth>e.clientWidth+2&&getComputedStyle(e).overflow!=='visible').length}));
 // primary count per scroll position
 await p.reload({waitUntil:'networkidle0'});await p.evaluate(()=>document.documentElement.style.scrollBehavior='auto');const prim=await p.evaluate(async()=>{const s=ms=>new Promise(r=>setTimeout(r,ms));const out=[];const H=document.documentElement.scrollHeight;for(let y=0;y<H;y+=200){scrollTo(0,y);await s(40);const vis=[...document.querySelectorAll('a.bg-brand-600, a[class*="bg-brand-600"]')].filter(a=>{const r=a.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight&&!a.closest('header')});out.push({y,primaries:vis.map(a=>a.textContent.trim())})}return out});R.primaryByScroll=prim.filter(o=>o.primaries.length);
 // focus rings (dark+light) on prev/next/cta
 for(const theme of ['dark','light']){await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await gotoScene(p,theme);const rings=[];for(const sel of ['[data-enter-cta]','[data-enter-prev]','[data-enter-next]']){await p.evaluate(s=>{document.querySelector(s).focus()},sel);await p.keyboard.press('Shift');rings.push(await p.evaluate(s=>{const e=document.querySelector(s);const cs=getComputedStyle(e);return s+': '+cs.outlineStyle+' '+cs.outlineWidth+' '+cs.outlineColor+' matches:'+e.matches(':focus-visible')},sel));}R['rings_'+theme]=rings;}
 await p.evaluate(()=>document.querySelector('[data-enter-next]').focus());await p.keyboard.press('Shift');await p.screenshot({path:`${OUT}/s4-focus-next.png`});
 // Tab order through scene
 await p.evaluate(()=>document.querySelector('[data-scene=choice] a[data-door]').focus());const order=[];for(let i=0;i<6;i++){await p.keyboard.press('Tab');order.push(await p.evaluate(()=>{const a=document.activeElement;return (a.getAttribute('data-enter-cta')!=null?'CTA ':a.getAttribute('data-enter-prev')!=null?'PREV ':a.getAttribute('data-enter-next')!=null?'NEXT ':'')+a.tagName+' "'+(a.textContent||'').trim().slice(0,30)+'" scene='+(a.closest('[data-scene]')?.getAttribute('data-scene'))}));}R.tabOrder=order;
 // SR reading order (text + roles)
 R.srOrder=await p.evaluate(()=>{const s=document.querySelector('[data-scene=enter]');const out=[];const walk=(n)=>{if(n.nodeType===1){const e=n;if(e.tagName==='STYLE'||e.tagName==='NOSCRIPT'||e.getAttribute('aria-hidden')==='true')return;const role=e.getAttribute('role')||({H2:'heading2',H3:'heading3',A:'link',BUTTON:'button',P:''})[e.tagName]||'';const lab=e.getAttribute('aria-label');if(role||lab)out.push(`[${role}${lab?' aria-label="'+lab+'"':''}]`);if(e.matches('[data-switch-announce]'))out.push('[live polite] '+e.textContent);}if(n.nodeType===3&&n.textContent.trim())out.push(n.textContent.trim());for(const c of n.childNodes)walk(c)};walk(s);return out});
 R.hydrationHome=p._hyd;await p.close();}

/* 6. all-draft / all-ready extremes (dev frame) + contrast on stage text measured + network (webgl/canvas) */
for(const f of ['ready','draft']){const p=await newPage();await p.goto(U+`/dev/scene-enter?frame=1&force=${f}`,{waitUntil:'networkidle0'});await sleep(400);R['force_'+f]=await p.evaluate(()=>({cta:document.querySelector('[data-enter-cta]')?.textContent||null,status:document.querySelector('[data-enter-status]')?.textContent||null,focusable:[...document.querySelectorAll('[data-enter-identity] a,[data-enter-identity] button')].length,depth:document.querySelector('[data-enter-depth]')?.textContent}));await p.screenshot({path:`${OUT}/s4-force-${f}.png`});await p.close();}
{const p=await newPage();const reqs=[];p.on('request',r=>reqs.push(r.url()));await p.goto(U+'/',{waitUntil:'networkidle0'});await p.evaluate(()=>document.querySelector('[data-scene=enter]').scrollIntoView());await sleep(1500);await p.evaluate(()=>document.querySelector('[data-enter-next]').click());await sleep(1500);
 R.network={requests:reqs.length,webglOrAmbient:reqs.filter(u=>/three|webgl|ambient|canvas|gl-/i.test(u)),canvasInPage:await p.evaluate(()=>document.querySelectorAll('canvas').length),webglCtx:await p.evaluate(()=>{const c=document.createElement('canvas');return 'probe-only'})};
 // measured contrast for stage text on actual pixel bg
 const lum=(r,g,bl)=>{const f=v=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4};return .2126*f(r)+.7152*f(g)+.0722*f(bl)};
 R.stageContrast={};for(const theme of ['dark','light']){await p.evaluate(t=>document.documentElement.setAttribute('data-theme',t),theme);await sleep(200);R.stageContrast[theme]=await p.evaluate(()=>{const rgb=s=>s.match(/\d+(\.\d+)?/g).map(Number);const bgOf=el=>{let e=el;while(e){const c=getComputedStyle(e).backgroundColor;const v=rgb(c);if(v&&v[3]!==0&&!(v.length===4&&v[3]===0))return c;e=e.parentElement}return null};const surf=getComputedStyle(document.querySelector('[data-scene=enter] [data-switch-layer]')).backgroundColor;return ['[data-enter-name]','[data-enter-env]','[data-enter-tagline]','[data-enter-depth]','[data-enter-status]','[data-enter-position]'].map(s=>{const e=document.querySelector(s);if(!e)return s+': —';return s+': '+getComputedStyle(e).color+' on '+surf})});}
 const cr=(a,b)=>{const L1=lum(...a),L2=lum(...b);return ((Math.max(L1,L2)+.05)/(Math.min(L1,L2)+.05)).toFixed(2)};for(const t of Object.keys(R.stageContrast))R.stageContrast[t]=R.stageContrast[t].map(l=>{const m=l.match(/rgba?\(([^)]+)\) on rgba?\(([^)]+)\)/);if(!m)return l;const a=m[1].split(',').map(Number),b=m[2].split(',').map(Number);return l.split(':')[0]+' '+cr(a,b)});
 await p.close();}
await b.close();fs.writeFileSync('/tmp/e1.out',JSON.stringify(R,null,1));console.log(JSON.stringify(R,null,1));})().catch(e=>{console.error(e);process.exit(1)});
