/* THE TUTOR'S STATES AS A SET (Phase 6 · Step 5 · Part 3) — the fourteen rows
 * of the brief, each with the surface, what renders, what it CLAIMS and the
 * test that proves it. Read by /dev/tutor-states and copied verbatim into
 * docs/STATE_LANGUAGE.md's 6.5 addendum. `verified` is "yes" | "untestable";
 * an untestable row carries its reason — never a fixture passed off as proof. */

export interface TutorState {
  n: number;
  state: string;
  surface: string;
  renders: string;
  claims: string;
  test: string;
  verified: "yes" | "untestable" | "recorded";
  reason?: string;
}

export const TUTOR_STATES: readonly TutorState[] = [
  { n: 1, state: "A read fails on the shell", surface: "/tutor", renders: "the honest page “Your students could not be read just now.” inside the tutor layout (tutor error boundary) — never state A from a failed read", claims: "nothing was recorded; opening again only reads", test: "tutor.cjs read-path gate; 5.7 row 24", verified: "yes" },
  { n: 2, state: "A read fails on the relationship’s surface", surface: "/tutor/[subject]/[relationship]", renders: "the reader throws DataReadError → the same tutor boundary → the same honest page (never 404: a failure is never “nobody here”)", claims: "nothing was recorded; a re-read is safe", test: "relationship.cjs (reader throws, not null); P5-R9", verified: "yes" },
  { n: 3, state: "A read fails on the shaping surface", surface: "/tutor/[subject]/environment", renders: "the honest page “This environment’s settings could not be read just now.” — NO FORM. The room may fall back to the authored default; a form pre-filled with it would invite an accidental revert", claims: "nothing was changed; the room still looks as it was set; a re-read is safe", test: "tutor-states.cjs shaping-read-failed (code gate on the branch + dev frame ?case=read-failed renders no <form>); log line scope page:/tutor/[subject]/environment", verified: "yes", reason: "the branch is proven by code + the dev frame; the trigger itself (a failing anon read) was not forced against production — recorded in “what was not tested”" },
  { n: 4, state: "A region fails", surface: "the relationship surface’s record (resolveRecord)", renders: "nothing in that region; one log line region:<id>. The primary answer (the student’s name, the subject, the position) is never silently absent — its read failing is row 2", claims: "an absent region claims nothing", test: "relationship.cjs region gate; isolate.ts is the one pattern", verified: "yes" },
  { n: 5, state: "The write is in flight", surface: "POST /tutor/[subject]/environment/shape", renders: "nothing of ours — a plain form POST, the browser’s own pending state (no client JS on the route)", claims: "this is being attempted, and nothing more", test: "tutor-states.cjs no-js-saves (scripts on the route = 0 of ours); write-unknown-outcome (abort mid-flight)", verified: "yes" },
  { n: 6, state: "The write failed, known", surface: "303 → /tutor/[subject]/environment?shape=failed", renders: "one sentence beside Save: “That did not save. The environment is unchanged — the values shown are the ones in force.” aria-describedby from the control; the row is untouched", claims: "no row changed; the values shown are in force", test: "tutor-states.cjs write-failed-known (unauthored value → 303 ?shape=failed; row before = row after)", verified: "yes" },
  { n: 7, state: "The write’s outcome is unknown", surface: "POST cut mid-flight", renders: "nothing of ours (the browser’s own failure); the settling GET — the shaping surface — shows the true state. No auto-retry", claims: "nothing — we do not know, so we say nothing; the next GET says what is true", test: "tutor-states.cjs write-unknown-outcome (request aborted; GET 200; no failed sentence; state line present)", verified: "yes" },
  { n: 8, state: "The session ended mid-save", surface: "POST with expired cookies", renders: "proxy 307 → /login?next=/tutor/[subject]/environment&reason=ended — the SETTLING GET, not the write URL. “That session ended. Signing in again goes back to the Physics environment.” Signing in lands on the shaping surface with the values in force; nothing was written", claims: "the session ended (a fact the proxy observed); where sign-in goes", test: "tutor-states.cjs write-session-ended (status chain, next param, sentence, row unchanged, landing after sign-in)", verified: "yes" },
  { n: 9, state: "A co-tutor changed the values between load and submit", surface: "POST → conditional write on subject_id + freshness token", renders: "the save is REFUSED (P6-R21, 2026-10-06): one 409 document — “Not saved” · “The room settings were updated in another session. Reload to review the current state before applying changes.” · one action back to the settling GET. Nothing written; the newer row stands", claims: "the room moved; the save did not land", test: "tutor-states.cjs write-concurrent (row changed by SQL as tutor U between load and submit; tutor T’s stale submit now meets the conditional write and is refused — gate asserts 409 + sentence + row untouched)", verified: "yes", reason: "ruling P6-R21 REFUSE_STALE_WRITE (DEC-018 addendum) closed the 6.5 §10 design decision; the gate is re-pinned to assert the refusal, harness re-run pending (no Chrome/DB in the current environment)" },
  { n: 10, state: "A relationship ends while the tutor has the page open", surface: "the next request to /tutor/[subject]/[relationship]", renders: "404 — the same bytes as never-related and nonexistent (P6-R9); the honest 404 page “There is no page at this address.” No sentence about the person; nothing the tutor could have caused", claims: "there is no page here", test: "identity-matrix.cjs ended-relationship cell = 404 for tutor T; relationship.cjs ended gate", verified: "yes" },
  { n: 11, state: "The tutor’s subject has no settings row", surface: "/tutor/[subject]/environment", renders: "the form with the authored values selected; “This environment is as authored.”; no Revert (nothing to put back)", claims: "a complete value — the authored default", test: "tutor-states.cjs write-unknown-outcome settledState (physics, no row) = “This environment is as authored.”; levers.cjs", verified: "yes" },
  { n: 12, state: "500 / 404 on each of the three routes", surface: "/tutor · /tutor/[subject]/[relationship] · /tutor/[subject]/environment", renders: "500: the tutor boundary’s honest page in the tutor layout. 404: the global honest 404 (notFound()) — client-rendered by the framework defect #99287, declared", claims: "nothing was recorded / there is no page here", test: "identity-matrix.cjs (404 cells); tutor.cjs read-path (500 path); 5.7 flip alarm", verified: "yes" },
  { n: 13, state: "No-JS and reduced motion across all three", surface: "all three", renders: "every state complete without JavaScript (server-rendered; no client JS on any tutor route); the settings form saves with JS off; reduced motion changes nothing on these surfaces (no motion on them)", claims: "nothing", test: "tutor-states.cjs no-js-saves; tutor.cjs / levers.cjs reduced-motion screenshots", verified: "yes" },
  { n: 14, state: "The role’s failure case", surface: "a student on a tutor route; a tutor on a student route", renders: "307 to the person’s own portal. No sentence, no page: the address was wrong, the person was not", claims: "nothing", test: "tutor-states.cjs role-crossing (6 rows, 0 alarm words); permissions.cjs", verified: "yes" },
];

export const FRAME_CASES = ["read-failed", "write-failed", "as-authored", "shaped-by-you", "shaped-by-other", "login-ended", "account"] as const;
export type FrameCase = (typeof FRAME_CASES)[number];
